### ISSUE TITLE
Version checking action throws `fatal: No tags can describe 'c6fe5614f71417e892afc6d1d1bd06711aad6232'.`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#1158]
From https://github.com/PolicyEngine/openfisca-us/runs/7472931404?check_suite_focus=true#step:6:12

@nikhilwoodruff could this be because the PR's commits predate the version check actions?

**Comment by nikhilwoodruff** [comment]
Oh that's fairly cryptic. I think yes - it's perhaps before we added tags, so the action can't find the last tag before the commits? I think a fix should be to effectively re-file in one commit (using `git reset`).

**Comment by nikhilwoodruff** [comment]
Just fixed it in that PR (the reason your PR didn't work is that it still used the old commits). What I did was:

```
git checkout master
git checkout snap-cbpp -- . <- A cool Git trick I found. If you pass -- after the branch name, it leaves the head alone, essentially just adding the difference between the target branch and the current branch as unstaged changes.
git branch -D snap-cbpp <- delete locally the snap-cbpp branch so we can overwrite it.
git checkout -b snap-cbpp <- re-create the branch
git commit -m ...
git push upstream snap-cbpp -f
```
