### ISSUE TITLE
What is the variable `dividend_income`?

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#1187]
There are four dividend income variables defined in OpenFisca-US, but only three make any sense to me.  I understand exactly what `qualified_dividend_income` and `non_qualified_dividend_income` are and I understand that `ordinary_dividend_income` is the sum of those two (as it's formula specifies).

But the `dividend_income` has no formula and I have no idea how it is taxed.  Is it taxed in the favorable way that `qualified_dividend_income` is?  Or is it taxed as regular income the same as `non_qualified_dividend_income`?

This is a mystery to me and I could not find any useful documentation to clear up my confusion.

I also am puzzled by the fact that dividends in the CPS are assigned to `dividend_income`, which seems to have an undefined tax status.   Seems like the CPS dividend amount should be assigned to `qualified_dividend_income` in a way that is similar to assigning CPS capital gains to the tax-favored long-term capital gains variable.

I would appreciate some clarification on these issues.

**Comment by nikhilwoodruff** [comment]
Thanks for identifying this Martin. I think what we should do is keep the `dividend_income` variable, but make it essentially the same as `ordinary_dividend_income`. For the units in the CPS, I think that we should split dividend income into a percentage qualified and non-qualified, based off whatever statistics we can find (we will improve this when we impute data from the PUF). I think this will fix any mishandling of dividends in the tax-benefit code.

**Comment by nikhilwoodruff** [comment]
@martinholmer actually, I think that ordinary dividends should refer to non-qualified dividends, and dividend income should be the sum of the two.

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #1187:
> @martinholmer actually, I think that ordinary dividends should refer to non-qualified dividends, and dividend income should be the sum of the two.

That is not true.  Ordinary dividends **include** qualified_dividends as you can see from looking at IRS Form 1040 and as described [here](https://en.wikipedia.org/wiki/Qualified_dividend).

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Here is an excerpt from the IRS instructions for 2021 Form 1040:

<img width="436" alt="Screen Shot 2022-07-29 at 8 52 00 AM" src="https://user-images.githubusercontent.com/12170745/181764666-e546153e-c4b9-44af-ae19-78a27c6bac4b.png">

As you can see, ordinary dividends is **not** the same as non-qualified dividends.

**Comment by martinholmer** [comment]
PR #1197 resolves issue #1187.
