### ISSUE TITLE
NY EITC

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#1241]
Mainly a match of the federal EITC. There are, however:

* For tax year 2021, a supplemental EITC which looks to be an additional percentage (25?)
* An enhanced EITC which disapplies a federal condition. However, this is only for taxpayers with children living away from home, so we can't model it in the microdata. Leaving for now. [Legislation](https://www.nysenate.gov/legislation/laws/TAX/606).

**Comment by MaxGhenis** [comment]
Duplicate of #863
