### ISSUE TITLE
OSError when running taxsim tests locally

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#1253]
When running `make test` and getting to the taxsim part:
>OSError: [Errno 8] Exec format error: '/Users/maxghenis/PolicyEngine/openfisca-us/openfisca_us/tools/dev/taxsim/taxsim35.exe'

I tried deleting taxsim35.exe, the h5 files, and running make install, but still get the error.

[Full log](https://gist.github.com/MaxGhenis/b0eb890232363ed30efc1be505e1f257)

**Comment by MaxGhenis** [comment]
[Asked on StackOverflow](https://stackoverflow.com/questions/73336040/oserror-errno-8-exec-format-error-when-calling-subprocess-popen-on-an-exe-fil)

**Comment by nikhilwoodruff** [comment]
Probably worth checking if you can actually run the taxsim.exe file normally using the instructions on NBER's site to check if it's a problem with the exe itself?

**Comment by MaxGhenis** [comment]
This was because we were using taxsim35-unix.exe for both Linux and Mac operating systems, instead of using taxsim35-osx.exe for Mac.

@feenberg - renaming taxsim35-unix.exe to taxsim35-linux.exe might avoid this issue for others in the future (since Mac is also unix).
