### ISSUE TITLE
Penn income tax forgiveness

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/openfisca-us#1256]
Thanks for filing an issue! Please remove any top-level headers that do not apply.

# Variable to add: name

# Variable to amend: name

# Parameter to add: name

# Parameter to amend: name
https://www.revenue.pa.gov/FormsandPublications/FormsforIndividuals/PIT/Documents/2021/2021_pa-40in.pdf#page=39

**Comment by MaxGhenis** [comment]
In the legal code, this is described as poverty income:
* https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/061/chapter123/chap123toc.html&d=
* https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/061/chapter101/chap101toc.html&d=
