### ISSUE TITLE
Establish whether NY CDCC uses federal rates

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#1316]
In the [2021 form](https://www.tax.ny.gov/pdf/current_forms/it/it216_fill_in.pdf), filers are directed to use a table in the [instructions](https://www.tax.ny.gov/pdf/current_forms/it/it216i.pdf#page=8) to find the federal CDCC rate (the percentage of expenses which are credited). But these only go up to 35%, whereas in 2021 the credit increased to a maximum of 50% under ARPA. I couldn't find anything in the [law](https://www.nysenate.gov/legislation/laws/TAX/606) which explicitly decoupled from federal law: it just references the IRC. Not an issue with 2022 law because the ARPA provision expired.

**Comment by MaxGhenis** [comment]
I also haven't been able to find the law, but this site describes the decoupling:

> For tax years beginning before January 1, 2022, the 2020-2021 New York State budget (Part WWW of Chapter 58 of the Laws of 2020) decoupled personal income tax from any amendments made to the Internal Revenue Code (IRC) after March 1, 2020. This includes changes made by the federal Coronavirus Aid, Relief, and Economic Security (CARES) Act and any other federal changes to the IRC. Therefore, any amendments made to the IRC after March 1, 2020, will not apply to New York State or New York City personal income tax.

https://www.tax.ny.gov/pit/file/income_tax_highlights.htm

**Comment by nikhilwoodruff** [comment]
Thanks: I followed through the links and found it: here's the [bill](https://www.nysenate.gov/legislation/bills/2019/S7508) and here's the [law](https://www.nysenate.gov/legislation/laws/TAX/607). I think that this means that the decoupling was only for 2021:
> Provided however, for
taxable years **beginning before January first, two thousand twenty-two** *(i.e. 2019, 2020, 2021)*,
any amendments made to the internal revenue code of nineteen hundred
eighty-six after March first, two thousand twenty shall not apply to
this article.

**Comment by MaxGhenis** [comment]
think we're good here
