### ISSUE TITLE
make install stuck

### ISSUE THREAD

**Issue by kfoster19** [PolicyEngine/openfisca-us#1319]
https://gist.github.com/kfoster19/7afb9eab37b24674d4d53eb3759eaa41

**Comment by MaxGhenis** [comment]
Ah shoot I forgot to downgrade to Python 3.7 with you, which is needed for OpenFisca.

Try this:
```shell
conda install python=3.7
```
Then run `make install` after that completes.

**Comment by MaxGhenis** [comment]
This worked
