### ISSUE TITLE
Model state TANF rules using Urban Institute Welfare Database

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/openfisca-us#134]
Upon review, the Urban Institute Welfare Database is only limited to AFDC/TANF benefit.

**Comment by MaxGhenis** [comment]
@nmrodelo could you try to [register for TRIM3](https://boreas.urban.org/Registration/)? That'll provide a database of program rules for other programs as modeled by TRIM3. (My account seems to be messed up.)

**Comment by MaxGhenis** [comment]
Here's what the [Policy Rules Database manual](https://www.atlantafed.org/-/media/documents/economic-mobility-and-resilience/advancing-careers-for-low-income-families/policy-rules-database/policy-rules-database-technical-manual.pdf) says about this:
>For example, the Urban Institute publishes annual data sets of Child Care and Development Fund (CCDF) and Temporary Assistance for Needy Families (TANF) policies but reflect outdated policy rules. These data sets also make extensive use of footnotes, which means these data can’t be easily used in software algorithms.

Per #139, they'll have TANF rules by November, so let's use PRD for this and spend the time until then on other programs.
