### ISSUE TITLE
SNAP shelter deduction

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#154]
Variable for shelter deduction

Start with some unit tests that take shelter costs and income as inputs, and produce shelter deduction as output:
1. Extreme cases (0, 1e6)
2. Something at the border (e.g. 50%)
3. Something in between

This can be located in `variables/finance/benefit/spm_unit/SNAP.py`. Code from openfisca-uk like [`child_benefit.py`](https://github.com/PolicyEngine/openfisca-uk/blob/master/openfisca_uk/variables/finance/benefit/family/child_benefit.py) could be helpful.

**Comment by nmrodelo** [comment]
can this be closed as well?

**Comment by MaxGhenis** [comment]
Yeah could you tie it to the relevant PR? I can't find it.

**Comment by nmrodelo** [comment]
> Yeah could you tie it to the relevant PR? I can't find it.

got it! see #171
