### ISSUE TITLE
Benefit unit level number of persons

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#16]
This goes into SNAP but is probably unnecessary as it can come from summing persons, is that right @nikhilwoodruff ?

**Comment by nikhilwoodruff** [comment]
Yep that's right:
`benunit.nb_persons()` is probably simplest, or
`benunit.sum(benunit.members("people"))` (this would just require adding a variable `people` at the person-level which always returns 1)

**Comment by nmrodelo** [comment]
Can we close this issue? @MaxGhenis @nikhilwoodruff
