### ISSUE TITLE
Add unit tests for the school lunch program variables

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#170]
- [x] spm_unit_school_meal_countable_income
- [ ] school_meal_subsidy
- [ ] spm_unit_school_meal_fpg_ratio
- [ ] spm_unit_school_meal_tier

**Comment by MaxGhenis** [comment]
Done: https://github.com/PolicyEngine/openfisca-us/tree/master/openfisca_us/tests/policy/baseline/usda/school_meals
