### ISSUE TITLE
SNAP Child/Dependent Care Deduction 

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/openfisca-us#181]

**Comment by nmrodelo** [comment]
Note this is not to be confused with the Child Support deduction, which is for parents that have monthly child support payments to another parent/legal guardian.

**Comment by nmrodelo** [comment]
Based on my exploration of the quality control data, still only 3.02% claim the dependent deduction, despite the fact that all elderly and child care expenses can be fully deducted

Some admin barrier to accessing this?

**Comment by MaxGhenis** [comment]
Done
