### ISSUE TITLE
Handle negative net income values when calculating SNAP Variables

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/openfisca-us#223]

**Comment by MaxGhenis** [comment]
@nmrodelo could you add some detail on this? Is the current approach inaccurate?

**Comment by nmrodelo** [comment]
Pretty sure we currently don't have a way to handle it. I think the max() we discussed last night should work

**Comment by nikhilwoodruff** [comment]
Nice- minor thing you probably already knew, but it'll need to be `max_` (vectorised) rather than the built-in `max`.

**Comment by MaxGhenis** [comment]
Let's check on this
