### ISSUE TITLE
Parametrize the capital loss limitation amount

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#258]
See:
* https://github.com/PolicyEngine/openfisca-us/pull/255#discussion_r750753451
* https://github.com/PSLmodels/Tax-Calculator/issues/2624

I think we should make a new parameter for the capital loss limitation amount, which is indexed by MARS.

Code currently lives here:
https://github.com/PolicyEngine/openfisca-us/blob/693ffb8486c1d62dbf24a5b2b157644620cd6328/openfisca_us/variables/irs/outputs.py#L530-L532

**Comment by MaxGhenis** [comment]
Done https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/gov/irs/ald/loss/capital/max.yaml
