### ISSUE TITLE
HHS household size adjustment parameters

### ISSUE THREAD

**Issue by tolaouk** [PolicyEngine/openfisca-us#263]
From [LIHEAP document](https://www.acf.hhs.gov/sites/default/files/documents/ocs/COMM_LIHEAP_IM03%20Attachment1%20SMITable_FY2022.pdf#page=3):
>State's estimated median income for a four- person family is multiplied by the following percentages to adjust for household size for LIHEAP: 52 percent for one person, 68 percent for two persons, 84 percent for three persons, 100 percent for four persons, 116 percent for five persons, and 132 percent for six persons. For each additional household member above six persons, add three percentage points to the percentage for a six-person household (132 percent)

**Comment by MaxGhenis** [comment]
done: https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/hhs/smi/household_size_adjustment.yaml
