### ISSUE TITLE
SNAP Utility Allowances ( + State Policy Options)

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/openfisca-us#271]
https://www.masslegalhelp.org/income-benefits/food-stamps/advocacy-guide/part3/q84-sua-heat-allowance

https://www.cbpp.org/research/food-assistance/a-quick-guide-to-snap-eligibility-and-benefits#_ftn15

https://snapqcdata.net/sites/default/files/2020-12/FY%202019%20SNAP%20QC%20Technical%20Documentation.pdf#page=165&zoom=100,93,96

**Comment by MaxGhenis** [comment]
Done except for a few that vary by household size or other factors, as listed in other issues
