### ISSUE TITLE
CCDF family income share by NY county

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#277]
This can be extracted from APUs in [this site](https://ocfs.ny.gov/programs/childcare/plans). For example, Allegany County's [2021 APU](https://ocfs.ny.gov/programs/childcare/plans/Allegany/Allegany1848.pdf#page=5) states "Family Share Percentage selected by the district: 10%" as of 2021-04-16.

@tolaouk heads up that their [2020 APU](https://ocfs.ny.gov/programs/childcare/plans/Allegany/Allegany1734.pdf#page=5) shows 20%, which matches the 2021-09-30 PRD (cell CCDF_NY!V5), so PRD might just be behind.

**Comment by tolaouk** [comment]
Thanks @MaxGhenis
