### ISSUE TITLE
Add inputs for tax variables

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#28]
On the microdata side, we're going to need survey inputs for the different tax variables used as input to tax logic. This will involve essentially trying to replicate `taxdata`'s process for the CPS. `taxdata` uses the same input dataset as us (the CPS), so to do this, we'll need to do the following for every variable in the [output dataset](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/cps.csv.gz):

1. Look at the [source code](https://github1s.com/pslmodels/taxdata/blob/HEAD/taxdata/cps/pycps.py#L178-L179) and understand the process of creating it from CPS variables
2. For every CPS variable used, add an OpenFisca variable to `openfisca-data` in `survey_input_variables.py` [like this](https://github.com/UBICenter/openfisca-data/blob/c50361549da5746307253feb7b8d9d8d805ebf55/openfisca_data/datasets/us/cps/base_cps/survey_input_variables.py#L5).
3. Add a variable to `model_input_variables.py` [like this](https://github.com/UBICenter/openfisca-data/blob/c50361549da5746307253feb7b8d9d8d805ebf55/openfisca_data/datasets/us/cps/base_cps/model_input_variables.py#L10).

This should be fairly procedural, but since `taxdata` iterates over rows rather than using Pandas (we're using Pandas), there might be instances where iterative approaches might be hard to replicate using vectorised functions: I'd advise to just skip those variables for now, and come back later to think about them.

**Comment by moon-home** [comment]
1. create_units() is processing a given data, but the example class created in survey_input_variables.py are only defining some attributes. Where should the processing logic go?
2. where to look up the meaning of those keys in create_units() data, such as a_spise, s_flag, etc?
3. where to look up definitions in raw data cps.csv? Most variables there are named with numbers, do I keep that convention or rename them to something meaningful?
4. There is cps.csv data and the spm uk data. for now, I will only need the first one? So is cps.csv data?

**Comment by nikhilwoodruff** [comment]
Relevant: [FPUS notebook](https://github.com/UBICenter/covid/tree/master/jb/fpuc)

**Comment by moon-home** [comment]
1. Should there be save() in raw_cps.py?
2. BaseCPS called inside BaseCPS?
3. I didn't see P_INT_VAL in raw_cps_2020.h5?
Notes: 
command to download the raw_cps_2020.h5:
`openfisca-data raw_cps generate 2020`
The h5 file should be located at `openfisca_data/microdata/external`

**Comment by nikhilwoodruff** [comment]
@moon-home the `P_` prefix is added to indicate the variable is at the person level (the raw dataset is a relational database with three tables: person, family, household). See [this part of dataset.py](https://github1s.com/ubicenter/openfisca-data/blob/HEAD/openfisca_data/datasets/us/cps/base_cps/dataset.py#L51-L60) for the code adding it.

**Comment by nikhilwoodruff** [comment]
All now added
