### ISSUE TITLE
Add CCDF's SMI eligibility variable

### ISSUE THREAD

**Issue by tolaouk** [PolicyEngine/openfisca-us#284]
For NY state:
https://www.ocfs.ny.gov/programs/childcare/stateplan/assets/2022-plan/FFY2022-2024-CCDF-Plan.pdf#page=66

**Comment by MaxGhenis** [comment]
Let's make this a single national variable for now.

Per sources in https://github.com/PolicyEngine/openfisca-us/issues/325, it was 75% of SMI in the original 1990 act (effective 1991), then raised to 85% in the 2014 act (effective 2015).
