### ISSUE TITLE
Unable to run tests locally

### ISSUE THREAD

**Issue by yvvijay121** [PolicyEngine/openfisca-us#333]
## Issue
I've been trying to run tests locally by using `make test` using the Makefile in the root directory, but I get this error when I run `make test`:
```
openfisca-us test openfisca_us/tests/policy
process_begin: CreateProcess(NULL, openfisca-us test openfisca_us/tests/policy, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:8: test] Error 2
```
Other `make` commands work properly, such as `make format`.
## Software Versions
I am currently using Python 3.7.9, although I also have Python 3.8.1 installed on my computer as the default Python version; therefore, I have to use `python3.7` and `pip3.7`. I installed `make` through Chocolatey v0.11.3. Output of `make --version`:
```
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by nikhilwoodruff** [comment]
OK, could you try the command executed by `make test`, `openfisca-us test openfisca_us/tests/policy`?

**Comment by yvvijay121** [comment]
Since I have to use Python 3.7 (the default installed Python version in my local environment is 3.8), do I have to use the command `python3.7 -m openfisca-us test openfisca-us/tests/policy`?

**Comment by nikhilwoodruff** [comment]
That should hopefully work- though I find it easier to use conda, e.g:
```bash
conda create -n python37 python=3.7
conda activate python37
(python37) $ make test
```

**Comment by yvvijay121** [comment]
It did! After switching to using a conda environment, everything works as expected. Thank you @nikhilwoodruff!
