### ISSUE TITLE
SNAP childcare deduction

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#376]

**Comment by MaxGhenis** [comment]
Per https://www.cbpp.org/research/the-food-stamp-dependent-care-deduction:
>Prior to 2008, the maximum dependent care deduction was $175 per month per dependent ($200 for infants). Effective October 1, 2008, the cap was eliminated, making a household’s entire dependent care cost eligible for the deduction.

**Comment by nikhilwoodruff** [comment]
Implemented at the federal level

**Comment by MaxGhenis** [comment]
The childcare deduction is implemented, just needs a formula pointing to childcare expenses (and maybe a parameter with a cap if we want pre-2008 rules).

**Comment by MaxGhenis** [comment]
Done https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/variables/usda/snap/income/deductions/snap_dependent_care_deduction.py
