### ISSUE TITLE
Add legislative references for SNAP

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#381]
Just looking through SNAP resources, in particular for some more legislative ones. While we'll reference state legislation for individual state-specific parameters and variables, it seems like the federal variables should reference federal law. On that front, here's a summary in case we don't already have it:
* The [Food Stamp Act of 1977](https://www.fns.usda.gov/snap/leghistory/food-stamp-act-1977-amended-dec-2000) seems to be the origination of most current SNAP federal rules
* This was amended and renamed to the [Food and Nutrition Act of 2008](https://www.fns.usda.gov/snap/fna-2008-amended-through-pl-116-94) by the [Food, Energy and Conservation Act of 2008](https://www.govinfo.gov/content/pkg/PLAW-110publ246/pdf/PLAW-110publ246.pdf#page=203) (page 203)
* Lots of other amendments since then

I found [this](https://uscode.house.gov/view.xhtml?path=/prelim@title7/chapter51&edition=prelim) page of house.gov, which seems to be pretty comprehensive. Should we use this as the primary source for our federal SNAP variables and parameters?

@MaxGhenis @nmrodelo anything I've missed here/how does this look?

**Comment by MaxGhenis** [comment]
Done
