### ISSUE TITLE
Policy Parameter to take into account elderly or disabled individual status in SNAP receiving households

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/openfisca-us#40]
There are significant differences between calculating benefits for households with and without at least one elderly and/or disabled person. For example, for most states the standard shelter deduction is capped at 569 per month, unless the household has an elderly or disabled individual living in it, in which case there is no cap.  

Additionally, on the income eligibility page, there is a separate table for such households, with more generous income limits:
https://fns-prod.azureedge.net/sites/default/files/media/file/FY21-Income-Eligibility-Standards.pdf

Per the USDA, in 2018 roughly 23% of SNAP receiving households met this criteria, meaning it is not a fringe population.

https://www.fns.usda.gov/snap/characteristics-households-fy-2018#:~:text=Seven%20percent%20of%20all%20participants,households%20had%20earnings%20in%20FY2018.

**Comment by nmrodelo** [comment]
the shelter deduction is unclear:

this state level source for MA makes the claim:
https://www.masslegalhelp.org/income-benefits/food-stamps/advocacy-guide/part3/q85-shelter-deduction

but the USDA source does not include a separate chart:
https://fns-prod.azureedge.net/sites/default/files/media/file/FY21-Maximum-Allotments-Deductions.pdf

**Comment by MaxGhenis** [comment]
We've now implemented this
