### ISSUE TITLE
Shelter deduction double multiplying by 12 in output for households with disabled/elderly individuals

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/openfisca-us#414]
In #406:

Most tests are passing at this point, however there are persistent and unknown issues with the shelter deductions tests. Getting both the cases to work at the same time, with disabled shelter deduction and without it, has not been possible.

The error output is exactly 12 times what the expected output should be, leading me to think that the month multiplication is doubled somewhere, but I have looked and found nothing. 

Any insight here @MaxGhenis @nikhilwoodruff ?

**Comment by nmrodelo** [comment]
Note: #406 is currently passing that test because I have edited the error margin so that I could move on to other issues

**Comment by nikhilwoodruff** [comment]
Just looked at this - I agree difficult to spot! But I think it's the deduction cap application, that branch doesn't have a x12.
