### ISSUE TITLE
Provide guidance on whether to include parameters in variables formulas that don't use them

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#467]
Currently, we include the `parameters` arg in all variable formulas, even those that don't use parameters and therefore don't need the arg. Let's decide on a standard and document it.

Arguments for including extraneous `parameters`:
* Speeds up development by allowing copy/pasting of variable boilerplate
* Avoids errors from omitting parameters when they're needed
* More visually consistent code

Arguments for removing extraneous `parameters`:
* Avoids IDE complaints about unused args
* Encourages developers to consider when a variable uses parameters
* More concise code

I'd lean toward including them.

**Comment by nikhilwoodruff** [comment]
I find the arguments for including more persuasive, thanks for writing this up. I'd vote to include.

**Comment by MaxGhenis** [comment]
We've continued to include them.
