### ISSUE TITLE
SNAP COVID emergency allotments

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#474]
https://www.fns.usda.gov/snap/covid-19-emergency-allotments-guidance

https://www.snapscreener.com/?p=table lists the states participating and says:
>Many states are giving all SNAP recipients the maximum possible benefit amount for their household size due to COVID-19.

**Comment by MaxGhenis** [comment]
http://reg.summaries.guide/category/calfresh/ says:

> All households will receive at least the maximum CalFresh allotment.  Households eligible to receive the maximum allowable allotment based on household size are now eligible to receive an emergency allotment of $95 per month. Households who are not eligible to receive the maximum allowable allotment based on household size, but whose emergency allotment would be less than $95 per month to receive the maximum allotment, will receive additional CalFresh benefits to raise their emergency allotment to the $95 minimum.

**Comment by MaxGhenis** [comment]
Fixed for California in #518, still need to implement other states.

**Comment by benmolin** [comment]
This source is good, but it can be a month behind: https://www.fns.usda.gov/snap/covid-19-emergency-allotments-guidance

Some states do not submit their extension until near the end of the month -- for example you might not see a state listed for Feb until the 25th.

**Comment by MaxGhenis** [comment]
We implemented this a while ago
