### ISSUE TITLE
State-level cap on SNAP medical expense deduction

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#479]

**Comment by MaxGhenis** [comment]
@nmrodelo could you share a source for this? I don't see a cap in the [federal legislation](https://www.law.cornell.edu/uscode/text/7/2014#e_5), the [State Options Database](https://fns-prod.azureedge.net/sites/default/files/snap/14-State-Options.pdf#33), or the [SNAP Screener data](https://www.snapscreener.com/?p=table).

**Comment by nmrodelo** [comment]
@MaxGhenis I must have been mistaken, I thought it was mentioned by the CBPP but I can't find anything. Disregard
