### ISSUE TITLE
Implement `calcfunctions` from Tax-Calculator

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#50]
Implementing the logic and parameters from [calcfunctions.py](https://github1s.com/pslmodels/tax-calculator/blob/HEAD/taxcalc/calcfunctions.py) in `tax-calculator`. Each function needs to:
- Have input and output parameters and variables present in `openfisca-us`
- Be decomposed into a set of many-in, one-out functions, preserving the logic (tax-calculator functions can be many-in, many-out), by adding intermediate variables as OpenFisca variables
- Have iterative logic re-implemented in vectorised form in each formula
- Have any unit tests from [test_calcfunctions.py](https://github1s.com/pslmodels/tax-calculator/blob/HEAD/taxcalc/tests/test_calcfunctions.py) re-implemented in `openfisca-us`

**Comment by MaxGhenis** [comment]
Could we make this epic more precise? Is the goal implementing all Tax-Calculator functions?

**Comment by nikhilwoodruff** [comment]
@MaxGhenis I've just added to the description - yes, tax-calc logic is the aim here.
