### ISSUE TITLE
Add Child Tax Credit

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#510]
I think we should just implement the [CTC legislation](https://www.law.cornell.edu/uscode/text/26/24) in one go: taxcalc splits it across the AdditionalCTC, CTC_new, ChildDepTaxCredit functions.

**Comment by MaxGhenis** [comment]
Is CTC_new part of past or current law?

**Comment by nikhilwoodruff** [comment]
I think that function implements the "Special rules for 2021" part of the law.

**Comment by nikhilwoodruff** [comment]
Fixed by #493
