### ISSUE TITLE
Add parameter for % of AMI as defined by HUD

### ISSUE THREAD

**Issue by kvanalebeek** [PolicyEngine/openfisca-us#519]
https://www.law.cornell.edu/uscode/text/42/1437a#b_2_B

| Category | % of AMI |
| - | - |
| Extremely low | 30* | 
| Very low | 50 |
| Low | 80 |

*for extremely low, also should consult the poverty guidelines, updated here: https://www.law.cornell.edu/uscode/text/42/9902#2

**Comment by MaxGhenis** [comment]
Fixed
