### ISSUE TITLE
HUD elderly & disabled income exclusion parameter for public housing

### ISSUE THREAD

**Issue by kvanalebeek** [PolicyEngine/openfisca-us#521]
https://www.law.cornell.edu/uscode/text/42/1437a#b_5_A_i

| Category | Exclusion per household |
| - | - |
| Elderly* or disabled | $400 |

*elderly person(s) defined as 62 and older via: https://www.law.cornell.edu/uscode/text/42/1437a#b_3_D

**Comment by MaxGhenis** [comment]
Done https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/gov/hud/adjusted_income/deductions/elderly_disabled/amount.yaml
