### ISSUE TITLE
HUD minors, students, and persons with disabilities (U18) parameter for public housing

### ISSUE THREAD

**Issue by kvanalebeek** [PolicyEngine/openfisca-us#522]
https://www.law.cornell.edu/uscode/text/42/1437a#b_5_A_iv

| Category | Exclusion per person (not including HOH) |
| - | - |
| Minor (U18), student*, minor (U18) with disabilities | $480 |

*Student: attending school or vocational training on a full-time basis

**Comment by MaxGhenis** [comment]
Done https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/gov/hud/adjusted_income/deductions/dependent/amount.yaml
