### ISSUE TITLE
Add Adj

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#53]
Add the tax policy logic from the [Adj](https://github1s.com/pslmodels/tax-calculator/blob/HEAD/taxcalc/calcfunctions.py#L315) function in `tax-calculator`, including parameters, intermediate and output variables.

**Comment by MaxGhenis** [comment]
What's `Adj`?

**Comment by nikhilwoodruff** [comment]
@MaxGhenis added details to clarify - it's a function in `calcfunctions.py`.
