### ISSUE TITLE
Reduce duplicate WIC CPI uprating metadata entries

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#616]
Is there a way to just enter the uprating CPI once?

https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/usda/wic/value.yaml

**Comment by nikhilwoodruff** [comment]
Oh, there is now (not sure if there was at the time): the `propagate_metadata_to_children: true` field in parameter metadata copies metadata down to descendants.
