### ISSUE TITLE
Point `e32800` to `childcare_expenses`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#639]
So the CDCC works properly in PolicyEngine.

See:
https://github.com/PolicyEngine/openfisca-us/blob/c293b6e16f9c45ca64696d9522ead93e9c05d4d8/openfisca_us/variables/irs/credits/cdcc/cdcc.py#L41

and

https://github.com/PolicyEngine/openfisca-us/blob/357c02d83ffdcd20ce6c337e12cec5c3cf7befd1/openfisca_us/variables/irs/income/sources.py#L853-L860

and https://taxcalc.pslmodels.org/guide/input_vars.html#e32800

**Comment by nikhilwoodruff** [comment]
Fixed by #641
