### ISSUE TITLE
Separate employer from employee payroll tax

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#643]
Currently our payroll taxes are employee+employer, e.g. this 12.4% is 6.2% employee + 6.2% employer.

https://github.com/PolicyEngine/openfisca-us/blob/5be521275ed0cd6b7331004572c26465ad71be7b/openfisca_us/parameters/irs/payroll/fica/social_security/rate.yaml#L4

For the simple version of static reforms, let's only include employee-side.

**Comment by nikhilwoodruff** [comment]
Removing from PolicyEngine for now because I'd like to run-through the implementation and US-code-ify it.

**Comment by martinholmer** [comment]
Is open issue #643 still relevant?

**Comment by MaxGhenis** [comment]
No, we've now separated them: https://github.com/PolicyEngine/openfisca-us/tree/master/openfisca_us/parameters/gov/irs/payroll/social_security/rate
