### ISSUE TITLE
Parameterize hard-coded 1% in CDCC

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#656]
https://github.com/PolicyEngine/openfisca-us/blob/862a9a1e623e202d24e848bc6685d79326104111/openfisca_us/variables/irs/credits/cdcc/cdcc.py#L56-L58

Similarly the `1e2` here:
https://github.com/PolicyEngine/openfisca-us/blob/862a9a1e623e202d24e848bc6685d79326104111/openfisca_us/variables/irs/credits/cdcc/cdcc.py#L75-L78

I think this might refer to [this](https://www.law.cornell.edu/uscode/text/26/21#a_2):
>For purposes of paragraph (1), the term “[applicable percentage](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-419852869-1473528914&term_occur=999&term_src=title:26:subtitle:A:chapter:1:subchapter:A:part:IV:subpart:A:section:21)” means 35 percent reduced (but not below 20 percent) by 1 percentage point for each $2,000 (or fraction thereof) by which the taxpayer’s adjusted gross income for the [taxable year](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-1529535480-1473532762&term_occur=999&term_src=title:26:subtitle:A:chapter:1:subchapter:A:part:IV:subpart:A:section:21) exceeds $15,000.

and [this](https://www.law.cornell.edu/uscode/text/26/21#g_4_B):
>The term “[phaseout percentage](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-24311015-1473534682&term_occur=999&term_src=title:26:subtitle:A:chapter:1:subchapter:A:part:IV:subpart:A:section:21)” means 20 percent reduced (but not below zero) by 1 percentage point for each $2,000 (or fraction thereof) by which the taxpayer’s adjusted gross income for the [taxable year](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=26-USC-1529535480-1473532762&term_occur=999&term_src=title:26:subtitle:A:chapter:1:subchapter:A:part:IV:subpart:A:section:21) exceeds $400,000.

respectively.

**Comment by martinholmer** [comment]
CDCC issue #656, which was raised in early April of this year, seems to be resolved in the late-August code.  The two-tier phase-out is now in the [cdcc_rate formula](https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/variables/gov/irs/credits/cdcc/cdcc_rate.py), which contains no `0.01 *` or `/ 1e2` expressions.   If I'm not missing something, it seems as if issue #656 has been resolved and could be closed.

**Comment by MaxGhenis** [comment]
Yep, this is now parameterized here: https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/gov/irs/credits/cdcc/phase_out/rate.yaml

Thanks for checking @martinholmer
