### ISSUE TITLE
Changing CTC refundable phase-in rate from 15% to 5-100% has no effect

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#680]
From PolicyEngine US, [changing the CTC refundable phase-in rate from 15% to 0%](https://policyengine.org/us/household?ctc_refundable_phase_in_rate=0) has an impact on one-adult one-child households:

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/6076111/162851840-8a506425-d1f5-4a23-86e9-07f19f6af5b4.png">

Lowering it to [1](https://policyengine.org/us/household?ctc_refundable_phase_in_rate=1), [2](https://policyengine.org/us/household?ctc_refundable_phase_in_rate=2), [3](https://policyengine.org/us/household?ctc_refundable_phase_in_rate=3), and [4%](https://policyengine.org/us/household?ctc_refundable_phase_in_rate=4) also has an effect. But changing it to any other value, from [5%](https://policyengine.org/us/household?ctc_refundable_phase_in_rate=5) to [100%](https://policyengine.org/us/household?ctc_refundable_phase_in_rate=100), has no effect:

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/6076111/162852067-00d86809-1b16-4c64-b304-de2236b40611.png">

Is this expected?

**Comment by MaxGhenis** [comment]
Tax-Cruncher shows that raising the phase-in to 100% produces the expected effect of lowering taxes (increasing refunds) https://compute.studio/PSLmodels/Tax-Cruncher/875/
<img width="639" alt="image" src="https://user-images.githubusercontent.com/6076111/163016029-20eaca96-fa1f-46ba-8b2c-5b746a254275.png">

**Comment by nikhilwoodruff** [comment]
OK, here's what the 4% looks like, as expected: 
![image](https://user-images.githubusercontent.com/35577657/163016664-eed823b6-b88c-4d7d-aea9-ec4feb578eb5.png)

100% doesn't seem to change it though.
