### ISSUE TITLE
Add Parameters for SNAP Shelter Deduction

### ISSUE THREAD

**Issue by nmrodelo** [PolicyEngine/openfisca-us#69]
Create separate set of rules for households with at least one individual with disability status.

**Comment by nmrodelo** [comment]
https://www.fns.usda.gov/snap/allotment/COLA; https://fns-prod.azureedge.net/sites/default/files/media/file/FY21-Maximum-Allotments-Deductions.pdf

**Comment by nikhilwoodruff** [comment]
Fixed by #122
