### ISSUE TITLE
Add state code from FIPS

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#692]
CPS and ACS provide state FIPS code. To tie that to the two-letter state code we use, we could use the [`us` package](https://github.com/unitedstates/python-us) as:
```python
two_letter_code = pd.Series(fips).apply(
    lambda x: us.states.lookup(str(x).zfill(2)).name
).tolist()
```
per https://github.com/unitedstates/python-us/issues/42.

**Comment by nikhilwoodruff** [comment]
Ah- just implemented (or rather, copilot wrote and I checked) for the ACS in #690
