### ISSUE TITLE
Add variable for HUD low income eligibility

### ISSUE THREAD

**Issue by kvanalebeek** [PolicyEngine/openfisca-us#700]
# Variable to add: low-income
Annual income does not exceed 80 percent of the median income for the area / adjustments for smaller and larger families / can be HUD adjusted dependent on region

"No family other than a low income family is eligible for admission to the Section 8 project-based assistance programs." *Does not apply to Section 8 project-based voucher program. 

https://www.law.cornell.edu/definitions/index.php?width=840&height=800&iframe=true&def_id=92b1d9f6b641769721c51d594f90b707&term_occur=999&term_src=Title:24:Subtitle:A:Part:5:Subpart:F:Subjgrp:21:5.653

*Just for new enrollees*

**Comment by MaxGhenis** [comment]
Done
