### ISSUE TITLE
Validate against TAXSIM 35

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#704]
See http://users.nber.org/~taxsim/taxsim35/

and taxcalc's implementation: https://github.com/PSLmodels/Tax-Calculator/tree/master/taxcalc/validation/taxsim27

**Comment by nikhilwoodruff** [comment]
Starting with small elements of the tax code

**Comment by MaxGhenis** [comment]
Duplicate of #1074
