### ISSUE TITLE
Set minimum SNAP emergency allotment to $95 across all states

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#741]
AFAICT it's $95 everywhere it's in effect, per http://snapscreener.com (it's not in the table but every state I've checked mentions $95). @benmolin is that right?

**Comment by benmolin** [comment]
Yes, I think for all the states with the extensions, it is $95.

Official guidance on calculations. Only change is the 15% boost is gone since September 2021.
https://fns-prod.azureedge.us/sites/default/files/resource-files/snap-covid-emergency-allotments-phase-3-guidance.pdf
