### ISSUE TITLE
MA ACA logic

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#784]
## Legislation

[42 U.S. Code Subchapter IV](https://www.law.cornell.edu/uscode/text/42/chapter-157/subchapter-IV)

**Comment by martinholmer** [comment]
@MaxGhenis and @nikhilwoodruff,
If you plan to model the ACA premium tax credit, you might find it helpful to look at this [older OSPC-sponsored project](https://chiselapp.com/user/mrh/repository/OSPC-ACA) that did exactly that.

**Comment by nikhilwoodruff** [comment]
Thanks @martinholmer - hadn't seen this, looks like it'll be very helpful!

**Comment by nikhilwoodruff** [comment]
Now completed.
