### ISSUE TITLE
TANF docs are still the old md file instead of the ipynb

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#808]
I expected #807 to fix this, but https://policyengine.github.io/openfisca-us//programs/hhs/tanf.html still doesn't reflect the ipynb. Might need a `make documentation`?

**Comment by yvvijay121** [comment]
I don't think running `make documentation` locally would affect the openfisca.us docs since the output of `make documentation` is ignored by the Git repository. I also tried re-running the Github Pages' `pages-build-deployment` workflow, but it didn't update the website.

**Comment by yvvijay121** [comment]
Fixed.
