### ISSUE TITLE
Add environment.yml file in top-level directory

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#809]
`OpenFisca-US` can be run only under Python 3.7 according to the `setup.py` file.
That is quite a limiting restriction for many people.

Can you add an `environment.yml` file that would allow the creation of an environment suitable for `OpenFisca-US` using the `conda env create` command?

Or am I missing something?  Does the installation procedure somehow automatically create such an environment?

@MaxGhenis  @nikhilwoodruff

**Comment by nikhilwoodruff** [comment]
Hi @martinholmer - thanks, this is a good idea. In the meantime, I think that running `conda create -n openfisca-us python=3.7` and then `pip install openfisca-us`-ing should always generate a working environment with the package (but feel free to correct me if it doesn't work in all cases).

**Comment by martinholmer** [comment]
Thanks for your suggestion in issue #809, @nikhilwoodruff.

I created the environment as you suggested and then, following the instructions in the `README.md` file, executed the `pip install git+...` command.

It all worked, but I'm left in an unexpected place.

(1) I don't seem to have any of the OpenFisca-US source code.

(2) I do have an `openfisca-us` package installed in the environment, but it doesn't seem to do much:
```
(openfisca-us) OpenFisca-US% openfisca-us -h       
usage: openfisca-us [-h] {test} ...

positional arguments:
  {test}      Available commands
    test      Run OpenFisca YAML tests

optional arguments:
  -h, --help  show this help message and exit

(openfisca-us) OpenFisca-US% openfisca-us test
usage: openfisca-us test [-h] [-c COUNTRY_PACKAGE]
                         [-e [EXTENSIONS [EXTENSIONS ...]]]
                         [-r [REFORMS [REFORMS ...]]] [-n NAME_FILTER] [-p]
                         [--performance-graph] [--performance-tables] [-v]
                         [-o [ONLY_VARIABLES [ONLY_VARIABLES ...]]]
                         [-i [IGNORE_VARIABLES [IGNORE_VARIABLES ...]]]
                         path [path ...]
openfisca-us test: error: the following arguments are required: path
```

I have no idea what the `...` in the usage statement means, and because I can't find the source code, I can't provide a `path` which is required to run the tests.

What am I doing wrong?

@MaxGhenis

**Comment by martinholmer** [comment]
I'm closing the request for an `environment.yml` file that was filed in issue #809 because the approach suggested by @nikhilwoodruff is a better idea.

It would be helpful to people who want to start using OpenFisca-US if the `README.md` file could be patched along the following lines:

```
- To install, run `pip install git+https://github.com/policyengine/openfisca-us`.
+ To install, execute the following commands:
+ ```
+ conda create -n openfisca-us python=3.7
+ conda activate openfisca-us
+ pip install git+https://github.com/policyengine/openfisca-us
+ ```
```
