### ISSUE TITLE
Duplication of pandas requirement in the setup.py file

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#810]
No need to list `pandas` twice in the list of `setup.py` requirements.

<img width="846" alt="Screen Shot 2022-05-22 at 5 59 56 PM" src="https://user-images.githubusercontent.com/12170745/169717828-5d9fdbd3-a3a9-481b-abd9-cf0b89deac08.png">

**Comment by MaxGhenis** [comment]
Thanks @martinholmer! I removed the duplicate in #805, and also alphabetized it to avoid it in the future.
