### ISSUE TITLE
TANF is too high in CA

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#811]
Running `make documentation` on `tanf.ipynb` locally shows that we calculate the maximum TANF benefit for a two-person household in CA to be $1,242/mo:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/6076111/169746657-eeb3f9d6-cccc-446f-9a65-e33b7f525bf8.png">

But the parameters show the maximum is $733/mo:

https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/hhs/tanf/cash/amount/max.yaml#L3-L9

**Comment by MaxGhenis** [comment]
This is because `tanf_max_amount` points to the continuous eligibility income limit parameter rather than the max amount parameter. Fixing in #805. @yvvijay121 fyi

**Comment by yvvijay121** [comment]
Oh, I see where I went wrong. Thank you so much for correcting this! I'll also try to create unit tests for CA TANF later to test this and make sure that the calculations are as expected.

**Comment by MaxGhenis** [comment]
Thanks @yvvijay121 - heads up I did add a unit test for CA in #805.
