### ISSUE TITLE
Set default year of Microsimulation to 2022

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-us#835]

**Comment by MaxGhenis** [comment]
See https://github.com/PolicyEngine/openfisca-tools/issues/57

**Comment by martinholmer** [comment]
@nikhilwoodruff, Didn't you set the default Microsimulation year to 2022 in PR #665 that you merged on April 14th?  If so, can this issue be closed?

**Comment by MaxGhenis** [comment]
Yep we're set here:

https://github.com/PolicyEngine/openfisca-us/blob/6a784f6e63ed83c44637b19c7900635001c7b564/openfisca_us/api/microsimulation.py#L21
