### ISSUE TITLE
Add Massachusetts state medical expense deduction

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#845]
The [Massachusetts income tax form](https://www.mass.gov/doc/2021-form-1-massachusetts-resident-income-tax-return/download) includes exemption 2e:
>Medical/dental (from [U.S. Schedule A](https://www.irs.gov/pub/irs-pdf/f1040sa.pdf), line 4)

That's `medical_expense_deduction` in openfisca-us.

**Comment by nikhilwoodruff** [comment]
Found the legislation, looks like it is just the federal medical expense deduction (must itemize) https://malegislature.gov/Laws/GeneralLaws/PartI/TitleIX/Chapter62/Section3
