### ISSUE TITLE
OpenFisca-Core error message when using 0.69.0 version

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#846]
When I download the 0.69.0 source code and do a `pip install .` command in the top-level directory (something that I've been doing for some time now), I get this message for each test case in my YAML test file:
```
openfisca_core.errors.variable_name_config_error.VariableNameConflictError: Variable "meets_ssi_resource_test" is already defined. Use `update_variable` to replace it.
```
Does this have something to do with the enhancement included for the first time in this version?

@MaxGhenis @nikhilwoodruff

**Comment by MaxGhenis** [comment]
That error indicates that a variable is defined multiple times, which might mean you have some old files on your computer (I think a recent PR moved that variable's file to a new folder location, but it [only shows up once](https://github.com/PolicyEngine/openfisca-us/search?q=meets_ssi_resource_test) in the current package). Could you try deleting the package folder and reinstalling?

BTW I use `pip install -e .` to save the extra `pip install .` commands when updating.
