### ISSUE TITLE
Add new taxsim_tfica variable

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#847]
It would be extremely helpful for my testing if one extra variable could be added to the `variables/contrib/taxsim` directory.  The file name would be `taxsim_tfica.py` and the contents would be something like this (feel free to make stylistic or efficiency improvements):
```
from openfisca_us.model_api import *


class taxsim_tfica(Variable):
    value_type = float
    entity = TaxUnit
    label = "Employee share of FICA + SECA + Additional Medicare Tax"
    unit = USD
    definition_period = YEAR

    def formula(tax_unit, period, parameters):
        seca = aggr(tax_unit, period, ["self_employment_tax"])
        return tax_unit("employee_payroll_tax", period) + seca
```

@MaxGhenis @nikhilwoodruff

**Comment by MaxGhenis** [comment]
Granted! See https://github.com/PolicyEngine/openfisca-us/pull/850.

The `sum_of_variables` function aggregates as needed, so it supports a list of variables specified at different entities and sums them to the new variable's entity.

Also in case it saves some keystrokes, Nikhil and I watch all new issues and PRs in the repo so no need to tag us.

Happy to add anything else that would aid in your validation.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for PR #847.
This will make the validation work go much more smoothly.
