### ISSUE TITLE
EITC doesn't match taxsim for an example

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#856]
@martinholmer reported an ACTC bug in #848, which I've fixed in #855.

However, the EITC value from [his example](https://github.com/PolicyEngine/openfisca-us/issues/848#issue-1254382212) still failed, after fixing the ACTC bug.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #856:
> @martinholmer reported an ACTC bug in https://github.com/PolicyEngine/openfisca-us/issues/848, which I've fixed in https://github.com/PolicyEngine/openfisca-us/pull/855.
> 
> However, the EITC value from https://github.com/PolicyEngine/openfisca-us/issues/848#issue-1254382212 still failed, after fixing the ACTC bug.

Perhaps this is because the EITC bug reported in issue #839 has not been fixed.
