### ISSUE TITLE
MA charitable deduction

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#878]
https://www.mass.gov/info-details/mass-general-laws-c62-ss-3 subsection (B)(a)(13):

>(13) An amount equal to the amount of the charitable contribution deduction allowed or allowable to the taxpayer under section 170 of the Code; provided, however, that, in taxable years beginning on or after January 1, 2002, no such deduction shall be allowed in any taxable year unless the rate of tax on Part B taxable income in section 4 in the prior taxable year was equal to 5 per cent; and provided, further, that notwithstanding said section 170 of the Code, no deduction shall be allowed for contributions of household goods or used clothing, as those items are recognized under said section 170 of the Code. All requirements, conditions and limitations applicable to charitable contributions under the Code shall apply for purposes of determining the amount of the deduction under this subparagraph, except that taxpayers shall not be required to itemize their deductions in their federal income tax returns.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff I didn't see this in the live code, should it be there?

**Comment by nikhilwoodruff** [comment]
I think so - filed https://github.com/PolicyEngine/openfisca-us/pull/1071
