### ISSUE TITLE
2020 microsimulation has nonzero SNAP emergency allotments

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-us#921]
Our [parameters](https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/parameters/usda/snap/emergency_allotment/in_effect.yaml) show that SNAP emergency allotments took effect only in March 2020. However, a 2020 microsimulation shows $142 billion in SNAP emergency allotments ([notebook](https://colab.research.google.com/drive/1HQf7aRxgTbnwBlsK-hrutLKPe9_KBw3P?usp=sharing)). The [logic](https://github.com/PolicyEngine/openfisca-us/blob/master/openfisca_us/variables/gov/usda/snap/snap_emergency_allotment.py) looks sound. Aren't parameters taken as of Jan 1?

**Comment by nikhilwoodruff** [comment]
This is because the default behaviour is to load the data from the last available year (2020) but to calculate in 2022. If you add period=2020 to the .calc call, you'll get zero.
