### ISSUE TITLE
Incorrect 2021 US EITC parameter values for those with no children

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#987]
In the 0.83.4 code, at least two of the 2021 US EITC parameters for those with no children are incorrect.   Some of the 2021-only no-kids parameter changes are correct in the code, but the phase-in rate and the phase-out start amount are wrong.  There may be others that are wrong but these are the two that are causing OpenFisca-US to produce the wrong EITC amount in the test case presented below.

Please recheck the legislation to see why TPC and TAXSIM35 both think the 2021 no-kids parameters have the values shown in [this document](https://www.taxpolicycenter.org/statistics/eitc-parameters).

Here is the test case and the test results:
```
(openfisca-us) US% cat p21-id998.test.yaml 
# OpenFisca-US test file derived from p21.its.csv and p21.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/18/22) With TCJA

- name: Tax unit with taxsimid 998 from p21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 70
        employment_income: 10000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 765.00
    #tax_unit_taxable_unemployment_compensation: 0.00
    #tax_unit_taxable_social_security: 0.00
    #adjusted_gross_income: 10000.00
    #taxable_income: 0.00
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 1502.00
    income_tax: -2902.00

(openfisca-us) US% openfisca-us test p21-id998.test.yaml
...
============================= FAILURES ============================
___________________________ test session __________________________
~/work/OpenFisca-US/US/p21-id998.test.yaml:
  Test 'Tax unit with taxsimid 998 from p21.its.csv':
    income_tax@2021: [-765.] differs from -2902.0
      with an absolute margin [2137.] > 0.01
===================== short test summary info =====================
FAILED p21-id998.test.yaml::
======================== 1 failed in 0.59s ========================
```

The total 2021 income tax difference for this case is $2137, of which $1400 is the 2021 Recovery Rebate Credit, which is not being modeled by OpenFisca-US but is being included in the income tax as a refundable credit by TAXSIM35 as specified in the legislation.  Putting the $1400 aside leaves the difference at $737 with TAXSIM35 getting $1502 (the special 2021-only maximum credit for those with no kids) and OpenFisca-US getting $765 (because it is using an incorrect 2021 phase-in rate).

**Comment by nikhilwoodruff** [comment]
Thanks for filing, Martin. Do you know why exactly that table differs from the IRS data release [here](https://www.irs.gov/pub/irs-drop/rp-20-45.pdf#page=10)? We're using that as the source.

**Comment by martinholmer** [comment]
@nikhilwoodruff asked:
> Do you know why exactly that table differs from the IRS data release [here](https://www.irs.gov/pub/irs-drop/rp-20-45.pdf#page=10)?

No.  But my experience is that the final parameter values on the official IRS forms (and in TurboTax and all the other tax software) do occasionally differ from what IRS put in the earlier data document.  Not sure why that is true other than the fact that even IRS staff are human and make mistakes every once in a while.  Or maybe the differences have something to do with BLS revising its inflation statistics after the IRS data document has been published.

**In this case, I would imagine the 2021 one-year changes to the no-kids EITC parameters was passed into law __after__ IRS published its data document.**

What does the IRS **Code** say about these 2021 parameter values?

**Comment by nikhilwoodruff** [comment]
The code section is [here](https://www.law.cornell.edu/uscode/text/26/32), but for most inflation-adjusted parameters, the Code only specifies the initial values and the uprating method, and leaves it to the IRS to apply it.

**Comment by martinholmer** [comment]
@nikhilwoodruff, You are missing the point that there were **legislated changes** in 2021  EITC parameters for those with no children.  You have not looked at the IRS code closely enough to see, for example, the 2021 increase in the non-indexed EITC phase-in rate for those with no children.  Do you really think TPC and NBER just made up these changes?

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Thanks for the quick response to issue #987 in PR #991.
