### ISSUE TITLE
EITC joint_bonus parameter is misspecified as a scalar

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/openfisca-us#992]
The OpenFisca-US 0.84.3 release has the parameter `parameters/gov/irs/credits/eitc/phase_out/joint_bonus.yaml` as a scalar instead of a vector with different values for tax units with different numbers of EITC eligible children.  This can be seen by reading the IRS references cited in `joint_bonus.yaml` (and doing some subtraction) or by reading footnote 1 of [this TPC table](https://www.taxpolicycenter.org/statistics/eitc-parameters) of historical EITC parameter values.

It appears that the scalar value used now is for tax units with children, so the EITC amounts for those with no children can be incorrect in the years beginning with 2018.

**Comment by nikhilwoodruff** [comment]
Oh I see - so the law specifies the marriage bonus as an equal amount for childless/with-child filers, but the rounding rules are applied to the phase-out threshold after its addition, causing the actual parameters to differ by $10? Thanks for identifying, will file a PR shortly.

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #992:
> but the rounding rules are applied to the phase-out threshold after its [i.e., the no-kids EITC] addition, causing the actual parameters to differ [sometimes] by $10? 

Yes, I think you are right that this "discrepancy" is caused by the fact that originally tax units with no kids were not eligible for the EITC.  So, I guess that the "base year" for the indexing of the older with-kids parameters is different from the "base year" for indexing no-kids parameters.  Whatever the cause, the joint bonus for those with kids and for those with no kids can be different.

**Comment by nikhilwoodruff** [comment]
Yes, updated using the TPC numbers in #995. They didn't have 2022, so I calculated by subtracting the joint threshold from the single threshold for filers with and without children in the [IRS data release](https://www.irs.gov/pub/irs-drop/rp-21-45.pdf#page=10), finding them both to be $6,130.
